CHANGELOG.md
Cargo.lock
README.adoc
deploy/config-spec/properties.yaml
deploy/crd/trinocluster.crd.yaml
docs/modules/ROOT/pages/building.adoc
docs/modules/ROOT/pages/index.adoc
docs/modules/ROOT/pages/usage.adoc
examples/simple-trino-cluster.yaml
rust/crd/Cargo.toml
rust/crd/src/lib.rs
rust/operator-binary/Cargo.toml
rust/operator/Cargo.toml
rust/operator/src/lib.rs

fixes https://github.com/stackabletech/trino-operator/issues/28

Adapt to use docker image

---

CHANGELOG.md
Cargo.lock
deploy/helm/trino-operator/Chart.yaml
deploy/manifests/configmap.yaml
deploy/manifests/deployment.yaml
deploy/manifests/serviceaccount.yaml
rust/crd/Cargo.toml
rust/operator-binary/Cargo.toml
rust/operator/Cargo.toml

The previous release 0.1.0 was broken.

Release 0.2.0

---

CHANGELOG.md
deploy/helm/trino-operator/crds/crds.yaml
rust/crd/src/lib.rs

cherry picked from commit e44e98be006ec0082086c5442741b35822867811
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
Once the review is done, comment `bors r+` (or `bors merge`) to merge. [Further information](https://bors.tech/documentation/getting-started/#reviewing-pull-requests)

Add missing crd defaults to 23.4

---

docs/modules/trino/examples/getting_started/code/trino.yaml
docs/modules/trino/examples/getting_started/code/trino.yaml.j2
docs/modules/trino/examples/usage_guide/trino-insecure.yaml
docs/modules/trino/examples/usage_guide/trino-secure-internal-tls.yaml
docs/modules/trino/examples/usage_guide/trino-secure-tls-only.yaml
docs/modules/trino/examples/usage_guide/trino-secure-tls.yaml
docs/modules/trino/pages/usage_guide/catalogs/index.adoc
examples/simple-trino-cluster-authentication-opa-authorization-s3.yaml
examples/simple-trino-cluster-hive-ha-s3.yaml
examples/simple-trino-cluster-resource-limits.yaml
examples/simple-trino-cluster-s3.yaml
examples/simple-trino-cluster.yaml
rust/crd/src/affinity.rs
rust/crd/src/lib.rs
tests/templates/kuttl/authentication/create-trino-cluster.yaml.j2
tests/templates/kuttl/cluster-operation/10-install-trino.yaml.j2
tests/templates/kuttl/cluster-operation/20-stop-trino.yaml.j2
tests/templates/kuttl/cluster-operation/30-pause-trino.yaml.j2
tests/templates/kuttl/cluster-operation/40-restart-trino.yaml.j2
tests/templates/kuttl/logging/02-install-trino.yaml.j2
tests/templates/kuttl/orphaned-resources/1-install-trino.yaml.j2
tests/templates/kuttl/resources/10-install-trino.yaml.j2
tests/templates/kuttl/smoke/05-install-zookeeper.yaml.j2
tests/templates/kuttl/smoke/06-install-hdfs.yaml.j2
tests/templates/kuttl/smoke/08-install-hive.yaml.j2
tests/templates/kuttl/smoke/09-install-opa.yaml.j2
tests/templates/kuttl/smoke/10-install-trino.yaml.j2
tests/templates/kuttl/tls/10-install-trino.yaml.j2

Part of https://github.com/stackabletech/issues/issues/404
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

Update test and docs to use automatic stackableVersion

---

tests/test-definition.yaml

Part of https://github.com/stackabletech/issues/issues/404
Fixup of #455
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

 test: Fix test definitions 

---

Cargo.lock
Cargo.toml
deploy/helm/trino-operator/crds/crds.yaml
rust/crd/Cargo.toml
rust/operator-binary/Cargo.toml
tests/templates/kuttl/authentication/create-trino-cluster.yaml.j2

```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

bump: operator-rs. Switch to workspace dependencies.

---

CHANGELOG.md
deploy/config-spec/properties.yaml
deploy/helm/trino-operator/configs/properties.yaml
docs/modules/trino/pages/usage_guide/configuration.adoc
rust/crd/src/lib.rs
rust/operator-binary/src/controller.rs

CI: https://ci.stackable.tech/view/02%20Operator%20Tests%20(custom)/job/trino-operator-it-custom/93/
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

JVM config overrides

---

deploy/helm/trino-operator/crds/crds.yaml
docs/modules/trino/pages/usage_guide/listenerclass.adoc
docs/modules/trino/partials/nav.adoc
rust/crd/src/lib.rs

```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

ListenerClass docs

---

docs/modules/trino/pages/usage_guide/operations/graceful-shutdown.adoc

Fix gracefulShutdownTimeout docs

---

rust/operator-binary/src/authentication/password/file.rs
rust/operator-binary/src/command.rs
rust/operator-binary/src/controller.rs

Before: Total mess
After:
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

refactor: Make Pod commands more readable

---

Cargo.lock
Cargo.toml
rust/crd/src/lib.rs
rust/operator-binary/Cargo.toml
rust/operator-binary/src/authentication/mod.rs
rust/operator-binary/src/authentication/password/mod.rs
rust/operator-binary/src/catalog/mod.rs
rust/operator-binary/src/controller.rs
rust/operator-binary/src/operations/pdb.rs
rust/operator-binary/src/product_logging.rs

Part of https://github.com/stackabletech/product-config/issues/95

refactor: Use updated product-config

---

tests/templates/kuttl/smoke/05-install-zookeeper.yaml.j2

```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

Fix zk logging in smoke test

---

tests/templates/kuttl/authentication/00-rbac.yaml.j2
tests/templates/kuttl/authentication/03-install-test-trino.yaml
tests/templates/kuttl/logging/00-rbac.yaml.j2
tests/templates/kuttl/logging/03-install-trino-test-runner.yaml
tests/templates/kuttl/smoke/00-rbac.yaml.j2
tests/templates/kuttl/smoke/20-install-check.yaml
tests/templates/kuttl/tls/00-rbac.yaml.j2
tests/templates/kuttl/tls/20-install-check.yaml.j2
tests/test-definition.yaml

CI: https://ci.stackable.tech/view/02%20Operator%20Tests%20(custom)/job/trino-operator-it-custom/108/

Run helper Pods with service accounts.

---

docs/modules/trino/examples/getting_started/code/getting_started.sh
docs/modules/trino/examples/getting_started/code/getting_started.sh.j2
docs/modules/trino/examples/getting_started/code/install-operator-output.txt
docs/modules/trino/examples/getting_started/code/install-operator-output.txt.j2
docs/modules/trino/pages/getting_started/first_steps.adoc
docs/modules/trino/pages/getting_started/installation.adoc
docs/templating_vars.yaml

The listener-operator is now one of the fundamental operators, along with the commons- and secret-operators, and should be mentioned accordingly everywhere.
```[tasklist]
```
```[tasklist]
```

docs: Add listener-operator where missing

---

docs/modules/trino/pages/usage-guide/index.adoc
docs/modules/trino/pages/usage-guide/overrides.adoc
docs/modules/trino/partials/nav.adoc

fixes #475 
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

feat(docs): Added overrides docs

---

docs/modules/trino/pages/index.adoc

docs: Fix link to trino.io

---

CHANGELOG.md
deploy/helm/trino-operator/templates/_helpers.tpl
deploy/helm/trino-operator/templates/deployment.yaml
deploy/helm/trino-operator/templates/roles.yaml
deploy/helm/trino-operator/values.yaml

Part of: https://github.com/stackabletech/issues/issues/501

feat(helm): support labels in values.yaml

---

tests/test-definition.yaml

fix: upgrade zk to latest version in tests
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

fix: upgrade zk to latest version in tests

---

rust/operator-binary/src/controller.rs

```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

Add test to reproduce configOverrides at role level bug

---

docs/modules/trino/pages/index.adoc

```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

docs: update supported versions text

---

docs/modules/trino/pages/usage-guide/log_aggregation.adoc
docs/modules/trino/pages/usage-guide/monitoring.adoc
docs/modules/trino/pages/usage-guide/security.adoc

```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

docs: fix links

---

examples/simple-trino-cluster-hive-ha-s3.yaml
tests/templates/kuttl/opa-authorization/03-install-hive.yaml.j2
tests/templates/kuttl/smoke/08-install-hive.yaml.j2

```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

Fix integration tests with hive db credentials

---

CHANGELOG.md
Cargo.lock
Cargo.nix
Cargo.toml
crate-hashes.json
examples/simple-trino-cluster-authentication-opa-authorization-s3.yaml

Part of https://github.com/stackabletech/issues/issues/601
Bump dependencies ahead of the 24.7 release
```[tasklist]
```
```[tasklist]
```

chore: Bump stackable-operator and other dependencies

---

tests/templates/kuttl/logging/01-install-trino-vector-aggregator.yaml

Use Vector Helm chart version 0.34.0 (Vector 0.39.0) in the logging test
https://github.com/vectordotdev/helm-charts/blob/vector-0.34.0/CHANGELOG.md#vector-0340---2024-06-17
Implements stackabletech/docker-images#561
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

Use Vector Helm chart version 0.34.0 in the logging test

---

docs/modules/trino/examples/getting_started/code/getting_started.sh
docs/modules/trino/examples/getting_started/code/getting_started.sh.j2
docs/modules/trino/examples/getting_started/code/install-operator-output.txt
docs/modules/trino/examples/getting_started/code/install-operator-output.txt.j2
docs/modules/trino/examples/getting_started/code/install_output.txt
docs/modules/trino/examples/getting_started/code/install_output.txt.j2
docs/modules/trino/pages/getting_started/installation.adoc

docs(getting-started): update stackablectl op install output

---

deploy/helm/trino-operator/templates/roles.yaml

See: https://github.com/stackabletech/issues/issues/624
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

fix(helm): use same scc as olm

---

CHANGELOG.md
Cargo.lock
Cargo.nix
Cargo.toml
crate-hashes.json
rust/operator-binary/src/controller.rs
tests/templates/kuttl/smoke/10-install-trino.yaml.j2
tests/templates/kuttl/smoke/11-assert.yaml

Part of: https://github.com/stackabletech/issues/issues/548
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

fix: respect user defined envOverrides

---

CHANGELOG.md
rust/operator-binary/src/authentication/mod.rs
rust/operator-binary/src/authentication/password/ldap.rs
rust/operator-binary/src/catalog/config.rs
rust/operator-binary/src/command.rs

```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

fix: Don't print credentials to STDOUT during startup

---

tests/templates/kuttl/opa-authorization/trino_policies.rego
tests/templates/kuttl/opa-authorization/trino_rules/actual_permissions.rego

Part of https://github.com/stackabletech/opa-operator/issues/617
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

chore: Use UIF rego rule wrapper in tests

---

docs/modules/trino/pages/usage-guide/connect_to_trino.adoc

```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

docs: Document how to connect using OIDC

---

docs/modules/trino/pages/getting_started/index.adoc
docs/modules/trino/pages/getting_started/installation.adoc
docs/modules/trino/pages/index.adoc
docs/modules/trino/pages/reference/commandline-parameters.adoc
docs/modules/trino/pages/reference/environment-variables.adoc
docs/modules/trino/pages/usage-guide/catalogs/delta-lake.adoc
docs/modules/trino/pages/usage-guide/catalogs/generic.adoc
docs/modules/trino/pages/usage-guide/catalogs/google-sheets.adoc
docs/modules/trino/pages/usage-guide/catalogs/hive.adoc
docs/modules/trino/pages/usage-guide/catalogs/iceberg.adoc
docs/modules/trino/pages/usage-guide/catalogs/index.adoc
docs/modules/trino/pages/usage-guide/configuration.adoc
docs/modules/trino/pages/usage-guide/connect_to_trino.adoc
docs/modules/trino/pages/usage-guide/index.adoc
docs/modules/trino/pages/usage-guide/operations/graceful-shutdown.adoc
docs/modules/trino/pages/usage-guide/operations/index.adoc
docs/modules/trino/pages/usage-guide/operations/pod-disruptions.adoc
docs/modules/trino/pages/usage-guide/operations/pod-placement.adoc
docs/modules/trino/pages/usage-guide/security.adoc

```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

docs: improvements

---

tests/templates/kuttl/authentication/create-trino-cluster.yaml.j2
tests/templates/kuttl/cluster-operation/10-install-trino.yaml.j2
tests/templates/kuttl/cluster-operation/20-stop-trino.yaml.j2
tests/templates/kuttl/cluster-operation/30-pause-trino.yaml.j2
tests/templates/kuttl/cluster-operation/40-restart-trino.yaml.j2
tests/templates/kuttl/logging/03-install-trino.yaml.j2
tests/templates/kuttl/opa-authorization/20-install-trino.yaml.j2
tests/templates/kuttl/orphaned-resources/1-install-trino.yaml.j2
tests/templates/kuttl/resources/10-install-trino.yaml.j2
tests/templates/kuttl/smoke/10-install-trino.yaml.j2
tests/templates/kuttl/tls/10-install-trino.yaml.j2
tests/test-definition.yaml

Allow using custom images in tests

Allow using custom images in tests

---

CHANGELOG.md
rust/operator-binary/src/controller.rs
rust/operator-binary/src/main.rs

Part of: https://github.com/stackabletech/issues/issues/211
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

fix: invalid objects don't stop the reconciliation

---

docs/modules/trino/examples/getting_started/code/getting_started.sh
docs/modules/trino/examples/getting_started/code/install_output.txt

Part of https://github.com/stackabletech/issues/issues/647.

docs: Update release in getting_started

---

CHANGELOG.md
Cargo.lock
Cargo.nix
Cargo.toml
Makefile
crate-hashes.json
docs/modules/trino/examples/getting_started/code/getting_started.sh
docs/modules/trino/examples/getting_started/code/getting_started.sh.j2
docs/modules/trino/examples/usage-guide/trino-oidc-auth-snippet.yaml
examples/simple-trino-oauth2.yaml
rust/crd/src/authentication.rs
rust/operator-binary/src/authentication/mod.rs
rust/operator-binary/src/authentication/oidc/mod.rs
tests/templates/kuttl/authentication/create-authentication-classes.yaml.j2
tests/templates/kuttl/opa-authorization/03-install-hive.yaml.j2

Add the following PRs to the release 24.11:
* #668 
* #670 
* #672 
* #673

Update release branch

---

Cargo.lock
docs/modules/trino/pages/usage-guide/operations/graceful-shutdown.adoc

Part of: https://github.com/stackabletech/issues/issues/586
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

docs: update certificate lifetime user guide

---

CHANGELOG.md
Cargo.lock
Cargo.nix
Cargo.toml
deploy/helm/trino-operator/Chart.yaml
docs/modules/trino/examples/getting_started/code/getting_started.sh
docs/modules/trino/examples/getting_started/code/install_output.txt
docs/templating_vars.yaml
tests/release.yaml

> [!CAUTION]
> ## DO NOT MERGE MANUALLY!
> This branch will be merged (and the commit tagged) by stackable-utils once any necessary commits have been cherry-picked to here from the main branch.

release: 24.11.1-rc2

---

CHANGELOG.md
Cargo.lock
Cargo.nix
rust/operator-binary/src/command.rs
rust/operator-binary/src/controller.rs
tests/templates/kuttl/opa-authorization/04-install-keycloak.yaml.j2
tests/templates/kuttl/smoke/10-assert.yaml
tests/templates/kuttl/smoke/12-assert.yaml

Part of https://github.com/stackabletech/issues/issues/527
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

feat: run containerdebug in the background

---

tests/templates/kuttl/logging/01-install-trino-vector-aggregator.yaml

Part of https://github.com/stackabletech/docker-images/issues/967
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

chore: Update Vector to 0.43.1 in integration tests

---

tests/test-definition.yaml

Part of https://github.com/stackabletech/docker-images/issues/998
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

chore: bump opa to 1.0.1

---

docs/modules/trino/pages/usage-guide/catalogs/black-hole.adoc

Fixes https://github.com/stackabletech/trino-operator/issues/707
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

docs: Fix typo in catalog name blackhole -> backHole

---

tests/test-definition.yaml

Part of https://github.com/stackabletech/docker-images/issues/1020

chore: Update ZooKeeper to 3.9.3 pre-25.3.0

---

tests/test-definition.yaml

part of https://github.com/stackabletech/docker-images/issues/1019
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

chore: Update Hive to 4.0.1

---

CHANGELOG.md
Cargo.lock
Cargo.nix
Cargo.toml
deploy/helm/trino-operator/Chart.yaml
deploy/helm/trino-operator/crds/crds.yaml
docs/antora.yml
docs/modules/trino/examples/getting_started/code/getting_started.sh
docs/modules/trino/examples/getting_started/code/install_output.txt
docs/templating_vars.yaml
tests/release.yaml

> [!CAUTION]
> ## DO NOT MERGE MANUALLY!
> This branch will be merged (and the commit tagged) by stackable-utils once any necessary commits have been cherry-picked to here from the main branch.

chore: Release 25.3.0

---

tests/templates/kuttl/logging/01-install-trino-vector-aggregator.yaml

Part of: https://github.com/stackabletech/docker-images/issues/1146

chore: bump vector chart to 0.43.0

---

docs/modules/trino/examples/getting_started/code/trino.yaml.j2
docs/modules/trino/pages/usage-guide/catalogs/index.adoc

Part of https://github.com/stackabletech/docker-images/issues/1082
It was missed in https://github.com/stackabletech/trino-operator/pull/755

docs: Update product version

---

tests/templates/kuttl/tls/20-install-check.yaml.j2

test: Remove outdated runAsUser in tls test

---

CHANGELOG.md
Cargo.lock
Cargo.nix
Cargo.toml
deploy/helm/trino-operator/Chart.yaml
docs/modules/trino/examples/getting_started/code/getting_started.sh
docs/modules/trino/examples/getting_started/code/install_output.txt
docs/templating_vars.yaml
tests/release.yaml

> [!CAUTION]
> ## DO NOT MERGE MANUALLY!
> This branch will be merged (and the commit tagged) by stackable-utils once any necessary commits have been cherry-picked to here from the main branch.

chore: Release 25.7.0
