stackabletech/trino-operator

CHANGELOG.md, Cargo.lock, Cargo.toml, tests/kuttl-test.yaml.jinja2, tests/templates/kuttl/logging/01-install-trino-vector-aggregator.yaml, tests/templates/kuttl/logging/test_log_aggregation.py, tests/templates/kuttl/logging/trino-vector-aggregator-values.yaml.j2
CI: https://ci.stackable.tech/view/02%20Operator%20Tests%20(custom)/job/trino-operator-it-custom/88/
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
Once the review is done, comment `bors r+` (or `bors merge`) to merge. [Further information](https://bors.tech/documentation/getting-started/#reviewing-pull-requests)
=> Upgrade Vector

CHANGELOG.md, Cargo.lock, Cargo.toml, deploy/helm/trino-operator/crds/crds.yaml, docs/modules/trino/pages/operations/graceful-shutdown.adoc, docs/modules/trino/pages/operations/index.adoc, docs/modules/trino/partials/nav.adoc, rust/crd/src/lib.rs, rust/operator-binary/src/authentication/mod.rs, rust/operator-binary/src/controller.rs, rust/operator-binary/src/main.rs, rust/operator-binary/src/operations/graceful_shutdown.rs, rust/operator-binary/src/operations/mod.rs, tests/kuttl-test.yaml.jinja2, tests/templates/kuttl/cluster-operation/30-assert.yaml, tests/test-definition.yaml
Fixes https://github.com/stackabletech/trino-operator/issues/429
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> Use graceful shutdown for workers

CHANGELOG.md, Cargo.lock, Cargo.toml, deploy/helm/trino-operator/crds/crds.yaml, rust/crd/Cargo.toml, rust/crd/src/lib.rs, rust/operator-binary/src/controller.rs
Part of https://github.com/stackabletech/operator-rs/issues/649
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> refactor: Use new Duration struct from operator-rs

docs/modules/trino/examples/usage_guide/opa-bundle-trino-cm.yaml, docs/modules/trino/pages/usage_guide/security.adoc
fixes #477 
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> Enhance Trino-OPA docs

rust/operator-binary/src/authentication/mod.rs, rust/operator-binary/src/controller.rs, tests/templates/kuttl/authentication/create-trino-cluster.yaml.j2, tests/templates/kuttl/cluster-operation/10-install-trino.yaml.j2, tests/templates/kuttl/cluster-operation/20-stop-trino.yaml.j2, tests/templates/kuttl/cluster-operation/30-pause-trino.yaml.j2, tests/templates/kuttl/cluster-operation/40-restart-trino.yaml.j2, tests/templates/kuttl/logging/02-install-trino.yaml.j2, tests/templates/kuttl/orphaned-resources/1-install-trino.yaml.j2, tests/templates/kuttl/resources/10-install-trino.yaml.j2, tests/templates/kuttl/smoke/10-install-trino.yaml.j2, tests/templates/kuttl/tls/10-install-trino.yaml.j2, tests/templates/kuttl/tls/20-install-check.yaml.j2
- Add the password-update-container after trino container (to default into trino container)
- Set gracefulShutdownTimeout in every test to avoid running out of cpu / memory resources with terminating pods.
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> Fix kuttl tests

docs/modules/trino/pages/usage-guide/security.adoc
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> Fix header level for auth password docs

CHANGELOG.md, Cargo.lock, Cargo.toml, deploy/helm/trino-operator/crds/crds.yaml, rust/crd/src/authentication.rs, rust/crd/src/catalog/commons.rs, rust/crd/src/catalog/google_sheet.rs, rust/crd/src/catalog/hive.rs, rust/crd/src/catalog/iceberg.rs, rust/crd/src/catalog/mod.rs, rust/crd/src/lib.rs, rust/operator-binary/src/main.rs
Better CRD docs
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> feat: Better CRD docs

docs/modules/trino/examples/usage-guide/opa-bundle-trino-cm-428.yaml, examples/simple-trino-cluster-authentication-opa-authorization-s3.yaml
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> docs:  Add missing OPA rules for Trino batched API

CHANGELOG.md, rust/operator-binary/src/catalog/commons.rs
Related to https://github.com/stackabletech/trino-operator/issues/525 (not sure if it fixes it)
We already know this was needed when e.g. enabling Kerberos on HDFS, so we would have needed this change in any case in the future.
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> fix: Add core-site.xml when configuring HDFS connection

CHANGELOG.md, deploy/helm/trino-operator/crds/crds.yaml, docs/modules/trino/pages/usage-guide/catalogs/delta-lake.adoc, docs/modules/trino/pages/usage-guide/catalogs/hive.adoc, docs/modules/trino/pages/usage-guide/catalogs/iceberg.adoc, docs/modules/trino/pages/usage-guide/catalogs/index.adoc, docs/modules/trino/partials/nav.adoc, rust/crd/src/affinity.rs, rust/crd/src/catalog/delta_lake.rs, rust/crd/src/catalog/iceberg.rs, rust/crd/src/catalog/mod.rs, rust/operator-binary/src/catalog/config.rs, rust/operator-binary/src/catalog/delta_lake.rs, rust/operator-binary/src/catalog/iceberg.rs, rust/operator-binary/src/catalog/mod.rs
Closes https://github.com/stackabletech/trino-operator/issues/352
Basically copy/paste from Iceberg, as the configuration is the same
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> feat: Add support for Delta Lake connector

tests/release.yaml, tests/templates/kuttl/authentication/00-patch-ns.yaml.j2, tests/templates/kuttl/authentication/05-install-test-trino.yaml, tests/templates/kuttl/authentication/05-install-test-trino.yaml.j2, tests/templates/kuttl/authentication/install-openldap-other.yaml.j2, tests/templates/kuttl/authentication/install-openldap.yaml.j2, tests/templates/kuttl/cluster-operation/00-patch-ns.yaml.j2, tests/templates/kuttl/logging/00-patch-ns.yaml.j2, tests/templates/kuttl/opa-authorization/00-patch-ns.yaml.j2, tests/templates/kuttl/orphaned-resources/00-patch-ns.yaml.j2, tests/templates/kuttl/resources/00-patch-ns.yaml.j2, tests/templates/kuttl/smoke/00-patch-ns.yaml.j2, tests/templates/kuttl/tls/00-patch-ns.yaml.j2, tests/test-definition.yaml
Part of stackabletech/issues#566.
OKD:
```
--- FAIL: kuttl (1844.11s)
--- FAIL: kuttl/harness (0.00s)
--- PASS: kuttl/harness/cluster-operation_trino-latest-442_openshift-true (140.09s)
--- PASS: kuttl/harness/orphaned-resources_trino-latest-442_openshift-true (89.51s)
--- PASS: kuttl/harness/logging_trino-442_openshift-true (73.77s)
--- PASS: kuttl/harness/tls_trino-latest-442_use-authentication-false_use-tls-true_use-internal-tls-true_openshift-true (66.05s)
--- PASS: kuttl/harness/opa-authorization_trino-latest-442_hive-3.1.3_opa-0.61.0_keycloak-23.0.1_openshift-true (541.64s)
--- PASS: kuttl/harness/resources_trino-latest-442_openshift-true (91.95s)
--- FAIL: kuttl/harness/authentication_trino-latest-442_ldap-use-tls-true_openshift-true (310.33s)
--- FAIL: …
```
=> tests: added namespace patch for openshift tests

CHANGELOG.md, docs/modules/trino/pages/usage-guide/operations/graceful-shutdown.adoc, rust/operator-binary/src/operations/graceful_shutdown.rs
Part of https://github.com/stackabletech/trino-operator/issues/574
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> chore!: Change graceful shutdown username to graceful-shutdown-user

tests/templates/kuttl/opa-authorization/11-opa-rego.yaml, tests/templates/kuttl/opa-authorization/trino_policies.rego, tests/templates/kuttl/opa-authorization/trino_rules/actual_permissions.rego, tests/templates/kuttl/opa-authorization/trino_rules/actual_permissions_test.rego, tests/templates/kuttl/opa-authorization/trino_rules/policies.rego, tests/templates/kuttl/opa-authorization/trino_rules/policies_test.rego
Grant the privileges required for graceful shutdowns to the admin user in the OPA rego rules
Required for #574 
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> Grant the privileges required for graceful shutdowns to the admin user in the OPA rego rules

tests/test-definition.yaml
Fixing Trino versions to string `442 -> "442"`
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> Trino versions explicitly to string

docs/modules/trino/examples/usage-guide/trino-insecure.yaml, docs/modules/trino/examples/usage-guide/trino-secure-internal-tls.yaml, docs/modules/trino/examples/usage-guide/trino-secure-tls-only.yaml, docs/modules/trino/examples/usage-guide/trino-secure-tls.yaml, examples/simple-trino-cluster-authentication-opa-authorization-s3.yaml, examples/simple-trino-cluster-hive-ha-s3.yaml, examples/simple-trino-cluster-s3.yaml, examples/simple-trino-cluster.yaml, tests/templates/kuttl/opa-authorization/03-install-hive.yaml.j2, tests/templates/kuttl/smoke/04-prepare-bucket.yaml.j2, tests/templates/kuttl/smoke/09-install-opa.yaml.j2, tests/templates/kuttl/smoke/check-s3.py, tests/test-definition.yaml
Part of https://github.com/stackabletech/issues/issues/620
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> chore: Bump to Hive 4.0.0

docs/modules/trino/pages/concepts.adoc, docs/modules/trino/pages/getting_started/first_steps.adoc, docs/modules/trino/pages/getting_started/index.adoc, docs/modules/trino/pages/getting_started/installation.adoc, docs/modules/trino/pages/index.adoc, docs/modules/trino/pages/usage-guide/configuration.adoc, docs/modules/trino/pages/usage-guide/connect_to_trino.adoc, docs/modules/trino/pages/usage-guide/log_aggregation.adoc, docs/modules/trino/pages/usage-guide/monitoring.adoc, docs/modules/trino/pages/usage-guide/query.adoc, docs/modules/trino/pages/usage-guide/s3.adoc, docs/modules/trino/pages/usage-guide/security.adoc
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> Add descriptions

tests/templates/kuttl/smoke/check-s3.py
Part of https://github.com/stackabletech/trino-operator/issues/648
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> test: Add test to check Trino version reporting

docs/modules/trino/examples/getting_started/code/getting_started.sh, docs/modules/trino/examples/getting_started/code/getting_started.sh.j2
Part of https://github.com/stackabletech/issues/issues/611.
Depends on https://github.com/stackabletech/trino-operator/pull/670.
=> chore(getting_started): Replace templating instructions with make

CHANGELOG.md, Cargo.lock, Cargo.nix, Cargo.toml, crate-hashes.json, docs/modules/trino/examples/usage-guide/trino-oidc-auth-snippet.yaml, examples/simple-trino-oauth2.yaml, rust/crd/src/authentication.rs, rust/operator-binary/src/authentication/mod.rs, rust/operator-binary/src/authentication/oidc/mod.rs, tests/templates/kuttl/authentication/create-authentication-classes.yaml.j2
Part of https://github.com/stackabletech/operator-rs/pull/910
Before this PR the operator generated
`http-server.authentication.oauth2.issuer=https\://185.56.150.115\:30584/realms/demo/`
resulting in
`java.lang.IllegalStateException: Invalid response from OpenID Metadata endpoint. The value of the "issuer" claim in Metadata document different than the Issuer URL used for the Configuration Request.`
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> fix: Construction of OIDC endpoint when rootPath has a trailing slash

CHANGELOG.md, deploy/helm/trino-operator/crds/crds.yaml, rust/crd/src/lib.rs
As decided in https://github.com/stackabletech/decisions/issues/38
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> chore: Increase coordinator temporary credentials lifetime

docs/modules/trino/examples/usage-guide/opa-bundle-trino-cm.yaml, examples/simple-trino-cluster-authentication-opa-authorization-s3.yaml, tests/templates/kuttl/opa-authorization/trino_policies.rego, tests/templates/kuttl/opa-authorization/trino_rules/actual_permissions.rego, tests/templates/kuttl/opa-authorization/trino_rules/actual_permissions_test.rego, tests/templates/kuttl/opa-authorization/trino_rules/policies.rego, tests/templates/kuttl/opa-authorization/trino_rules/policies_test.rego, tests/templates/kuttl/opa-authorization/trino_rules/requested_permissions.rego, tests/templates/kuttl/opa-authorization/trino_rules/requested_permissions_test.rego, tests/templates/kuttl/opa-authorization/trino_rules/util.rego, tests/templates/kuttl/opa-authorization/trino_rules/util_test.rego, tests/templates/kuttl/opa-authorization/trino_rules/verification.rego, tests/templates/kuttl/opa-authorization/trino_rules/verification_test.rego, tests/templates/kuttl/smoke/09-install-opa.yaml.j2, tests/test-definition.yaml
Part of: https://github.com/stackabletech/docker-images/issues/969
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> chore(opa) bump to 1.0.0 in integration tests and docs

CHANGELOG.md, Cargo.nix, rust/operator-binary/src/controller.rs
Fixup of #715
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> fix: Set correct schema in startup probe

tests/templates/kuttl/opa-authorization/02-install-minio.yaml.j2, tests/templates/kuttl/opa-authorization/check-opa.py
Integration test had errors:
- `Caused by: software.amazon.awssdk.services.s3.model.S3Exception: Missing required header for this request: Content-Md5` -> fixed by minio version bump https://github.com/minio/minio/issues/20845#issuecomment-2604259537
- Support for `optimize_hash_generation` was removed in Trino 470 https://trino.io/docs/current/release/release-470.html
- Fixed `AssertionError: Regex pattern did not match. Regex: "Session property 'iceberg.test' does not exist"`
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> chore: fix integration test

CHANGELOG.md, docs/modules/trino/pages/usage-guide/configuration.adoc, rust/operator-binary/src/authorization/opa.rs, rust/operator-binary/src/controller.rs, rust/operator-binary/src/crd/mod.rs
Implementation for https://github.com/stackabletech/trino-operator/issues/692
```
--- FAIL: kuttl (1731.56s)
--- FAIL: kuttl/harness (0.00s)
--- PASS: kuttl/harness/cluster-operation_trino-latest-470_openshift-false (73.45s)
--- PASS: kuttl/harness/tls_trino-latest-470_use-authentication-false_use-tls-true_use-internal-tls-true_openshift-false (73.56s)
--- PASS: kuttl/harness/logging_trino-470_openshift-false (70.66s)
--- PASS: kuttl/harness/authentication_trino-latest-470_ldap-use-tls-false_openshift-false (265.89s)
--- PASS: kuttl/harness/logging_trino-455_openshift-false (69.92s)
--- PASS: kuttl/harness/logging_trino-451_openshift-false (72.95s)
--- PASS: kuttl/harness/tls_trino-latest-470_use-authentication-true_use-tls-true_use-internal-tls-true_openshift-false (75.16s)
--- PASS: …
```
=> feat: Add access-control.properties overrides

CHANGELOG.md, Cargo.lock, Cargo.nix, Cargo.toml, crate-hashes.json
Part of <https://github.com/stackabletech/issues/issues/699>
> [!NOTE]
> During a Stackable release we need to update various Rust dependencies before
> entering the final release period to ensure we run the latest versions of
> crates. These bumps also include previously updated and released crates from
> the `operator-rs` repository.
```[tasklist]
```
> [!NOTE]
> The bumping / updating of Rust dependencies is done in multiple steps:
>
> 1. Update the minimum Version in the root `Cargo.toml` manifest.
> 2. Run the `cargo update` command, which also updates the `Cargo.lock` file.
> 3. Lastly, run `make regenerate-nix` to update the `Cargo.nix` file.
```[tasklist]
```
=> chore: Bump Rust dependencies pre-25.3.0

docs/modules/trino/partials/supported-versions.adoc
Part of <https://github.com/stackabletech/docker-images/issues/971>.
Mark Trino 455 as deprecated
=> docs: Mark Trino 455 as deprecated

tests/templates/kuttl/opa-authorization/20-install-trino.yaml.j2, tests/templates/kuttl/opa-authorization/check-opa.py.j2, tests/test-definition.yaml
Follow up of this comment https://github.com/stackabletech/trino-operator/pull/720#pullrequestreview-2681191722
Run opa-authorization tests for all supported Trino versions.
```
--- PASS: kuttl (320.63s)
--- PASS: kuttl/harness (0.00s)
--- PASS: kuttl/harness/opa-authorization_trino-455_hive-latest-4.0.1_opa-1.0.1_keycloak-25.0.0_openshift-false (307.00s)
--- PASS: kuttl/harness/opa-authorization_trino-470_hive-latest-4.0.1_opa-1.0.1_keycloak-25.0.0_openshift-false (310.35s)
--- PASS: kuttl/harness/opa-authorization_trino-451_hive-latest-4.0.1_opa-1.0.1_keycloak-25.0.0_openshift-false (320.62s)
PASS
```
- Please make sure all these things are done and …
=> chore: expand opa-authorization test to run with all supported trino versions

docs/modules/trino/examples/getting_started/code/getting_started.sh, docs/modules/trino/examples/getting_started/code/getting_started.sh.j2, docs/modules/trino/pages/getting_started/installation.adoc, docs/templating_vars.yaml
Part of https://github.com/stackabletech/infrastructure/issues/142
Updating the helm install commands in Getting started sections of the operators was missed during Harbor migration of the docs.
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> docs: Update helm install commands

CHANGELOG.md, tests/test-definition.yaml
Part of https://github.com/stackabletech/hdfs-operator/pull/675.
- Bump HDFS to 3.4.1
=> test: Bump HDFS to 3.4.1

CHANGELOG.md, tests/templates/kuttl/logging/01-install-trino-vector-aggregator.yaml
Part of https://github.com/stackabletech/docker-images/issues/1085.
- Bump to Vector 0.46.1 (chart version 0.42.1) in tests
=> test: Bump vector to 0.46.1

CHANGELOG.md, tests/templates/kuttl/opa-authorization/10-install-opa.yaml.j2, tests/test-definition.yaml
Part of https://github.com/stackabletech/docker-images/issues/1084.
- Bump OPA to 1.4.2 in tests.
=> test: Bump OPA to 1.4.2

CHANGELOG.md, Cargo.lock, Cargo.nix, Cargo.toml, crate-hashes.json, deploy/helm/trino-operator/crds/crds.yaml, rust/operator-binary/src/authentication/mod.rs, rust/operator-binary/src/authentication/oidc/mod.rs, rust/operator-binary/src/authentication/password/file.rs, rust/operator-binary/src/authentication/password/ldap.rs, rust/operator-binary/src/authentication/password/mod.rs, rust/operator-binary/src/catalog/commons.rs, rust/operator-binary/src/catalog/mod.rs, rust/operator-binary/src/controller.rs, rust/operator-binary/src/crd/authentication.rs, rust/operator-binary/src/crd/catalog/delta_lake.rs, rust/operator-binary/src/crd/catalog/hive.rs, rust/operator-binary/src/crd/catalog/iceberg.rs, rust/operator-binary/src/crd/mod.rs, rust/operator-binary/src/main.rs
Part of https://github.com/stackabletech/issues/issues/642.
Bump stackable-operator to 0.93.0 which versions common CRD structs.
=> chore: Bump stackable_operator to 0.93.1

CHANGELOG.md, docs/modules/trino/examples/getting_started/code/trino.yaml, docs/modules/trino/examples/usage-guide/trino-insecure.yaml, docs/modules/trino/examples/usage-guide/trino-secure-internal-tls.yaml, docs/modules/trino/examples/usage-guide/trino-secure-tls-only.yaml, docs/modules/trino/examples/usage-guide/trino-secure-tls.yaml, docs/modules/trino/partials/supported-versions.adoc, examples/simple-trino-cluster-authentication-opa-authorization-s3.yaml, examples/simple-trino-cluster-hive-ha-s3.yaml, examples/simple-trino-cluster-resource-limits.yaml, examples/simple-trino-cluster-s3.yaml, examples/simple-trino-cluster.yaml, examples/simple-trino-oauth2.yaml, rust/operator-binary/src/config/jvm.rs, tests/templates/kuttl/opa-authorization/check-opa.py.j2, tests/test-definition.yaml
Part of https://github.com/stackabletech/docker-images/issues/1082.
=> chore: Add 476, deprecate 470, remove 455

tests/templates/kuttl/opa-authorization/10-assert.yaml, tests/templates/kuttl/smoke/09-assert.yaml, tests/templates/kuttl/smoke_aws/09-assert.yaml
Latest weekly tests fail while waiting for the OPA Daemonsets to become ready.
For example: https://testing.stackable.tech/job/trino-operator-it-weekly/58/artifact/target/test-output.log/*view*/
It is worth knowing that the weekly tests require 10 nodes to run and this obviously puts a strain on `oci.stackable.tech`.
=> tests: increase OPA assert timeouts

CHANGELOG.md, Cargo.lock, Cargo.nix, Cargo.toml, crate-hashes.json, deploy/helm/trino-operator/crds/crds.yaml, deploy/helm/trino-operator/templates/roles.yaml, rust/operator-binary/src/command.rs, rust/operator-binary/src/crd/catalog/mod.rs, rust/operator-binary/src/crd/mod.rs, rust/operator-binary/src/listener.rs, rust/operator-binary/src/main.rs
Part of <https://github.com/stackabletech/issues/issues/TRACKING_ISSUE>
> [!NOTE]
> During a Stackable release we need to update various Rust dependencies before
> entering the final release period to ensure we run the latest versions of
> crates. These bumps also include previously updated and released crates from
> the `operator-rs` repository.
> [!NOTE]
> The bumping / updating of Rust dependencies is done in multiple steps:
>
> 1. Update the minimum Version in the root `Cargo.toml` manifest.
> 2. Run the `cargo update` command, which also updates the `Cargo.lock` file.
> 3. Lastly, run `make regenerate-nix` to update the `Cargo.nix` file.
=> chore: Bump Rust dependencies pre-25.7.0

examples/simple-trino-cluster-hive-ha-s3.yaml, examples/simple-trino-cluster-s3.yaml
Part of https://github.com/stackabletech/issues/issues/749 and follow up to https://github.com/stackabletech/trino-operator/pull/784
This PR updates the examples of the 25.7 release to use bitnamilegacy.
=> chore: update examples to use bitnamilegacy

CHANGELOG.md, docs/modules/trino/examples/getting_started/code/trino.yaml, docs/modules/trino/examples/getting_started/code/trino.yaml.j2, docs/modules/trino/examples/usage-guide/fault-tolerant-execution.yaml, docs/modules/trino/examples/usage-guide/trino-insecure.yaml, docs/modules/trino/examples/usage-guide/trino-secure-internal-tls.yaml, docs/modules/trino/examples/usage-guide/trino-secure-tls-only.yaml, docs/modules/trino/examples/usage-guide/trino-secure-tls.yaml, docs/modules/trino/pages/getting_started/installation.adoc, docs/modules/trino/pages/usage-guide/OpenTelemetry.adoc, docs/modules/trino/pages/usage-guide/catalogs/index.adoc, docs/modules/trino/pages/usage-guide/connect_to_trino.adoc, docs/modules/trino/partials/supported-versions.adoc, examples/simple-trino-cluster-authentication-opa-authorization-s3.yaml, examples/simple-trino-cluster-hive-ha-s3.yaml, examples/simple-trino-cluster-resource-limits.yaml, examples/simple-trino-cluster-s3.yaml, examples/simple-trino-cluster.yaml, examples/simple-trino-oauth2.yaml, rust/operator-binary/src/authentication/mod.rs, rust/operator-binary/src/authentication/password/mod.rs, rust/operator-binary/src/config/jvm.rs, rust/operator-binary/src/controller.rs, rust/operator-binary/src/crd/affinity.rs, rust/operator-binary/src/crd/mod.rs, tests/templates/kuttl/opa-authorization/check-opa.py.j2, tests/test-definition.yaml
Part of https://github.com/stackabletech/docker-images/issues/1242
Smoke tests with updated Trino, Trino CLI and Trino operator images passed:
```
--- PASS: kuttl (487.69s)
--- PASS: kuttl/harness (0.00s)
--- PASS: kuttl/harness/smoke_trino-477_hive-4.0.1_opa-1.4.2_hdfs-3.4.1_zookeeper-3.9.3_openshift-false (487.36s)
PASS
```
=> chore: Bump Trino version for 25.11.0

tests/test-definition.yaml
Part of https://github.com/stackabletech/docker-images/issues/1275
```
--- FAIL: kuttl (6518.83s)
--- FAIL: kuttl/harness (0.00s)
--- PASS: kuttl/harness/orphaned-resources_trino-latest-477_openshift-false (356.66s)
--- PASS: kuttl/harness/fault-tolerant-execution_trino-476_openshift-false (406.91s)
--- PASS: kuttl/harness/tls_trino-latest-477_use-authentication-false_use-tls-false_use-internal-tls-false_openshift-false (78.89s)
--- PASS: kuttl/harness/listener_trino-477_openshift-false (80.47s)
--- PASS: kuttl/harness/fault-tolerant-execution_trino-451_openshift-false (179.98s)
--- PASS: kuttl/harness/listener_trino-476_openshift-false (93.07s)
--- PASS: kuttl/harness/listener_trino-451_openshift-false (91.10s)
--- PASS: kuttl/harness/smoke_trino-451_hive-4.0.1_opa-1.8.0_hdfs-3.4.2_zookee …
```
=> chore: Bump zookeeper version for 25.11.0
